// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tonymj76/savannah/ent/commit"
	"github.com/tonymj76/savannah/ent/predicate"
)

// CommitUpdate is the builder for updating Commit entities.
type CommitUpdate struct {
	config
	hooks    []Hook
	mutation *CommitMutation
}

// Where appends a list predicates to the CommitUpdate builder.
func (cu *CommitUpdate) Where(ps ...predicate.Commit) *CommitUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetAuthor sets the "author" field.
func (cu *CommitUpdate) SetAuthor(a any) *CommitUpdate {
	cu.mutation.SetAuthor(a)
	return cu
}

// SetURL sets the "url" field.
func (cu *CommitUpdate) SetURL(s string) *CommitUpdate {
	cu.mutation.SetURL(s)
	return cu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (cu *CommitUpdate) SetNillableURL(s *string) *CommitUpdate {
	if s != nil {
		cu.SetURL(*s)
	}
	return cu
}

// SetDate sets the "date" field.
func (cu *CommitUpdate) SetDate(t time.Time) *CommitUpdate {
	cu.mutation.SetDate(t)
	return cu
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (cu *CommitUpdate) SetNillableDate(t *time.Time) *CommitUpdate {
	if t != nil {
		cu.SetDate(*t)
	}
	return cu
}

// Mutation returns the CommitMutation object of the builder.
func (cu *CommitUpdate) Mutation() *CommitMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommitUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommitUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommitUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CommitUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(commit.Table, commit.Columns, sqlgraph.NewFieldSpec(commit.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Author(); ok {
		_spec.SetField(commit.FieldAuthor, field.TypeJSON, value)
	}
	if value, ok := cu.mutation.URL(); ok {
		_spec.SetField(commit.FieldURL, field.TypeString, value)
	}
	if value, ok := cu.mutation.Date(); ok {
		_spec.SetField(commit.FieldDate, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CommitUpdateOne is the builder for updating a single Commit entity.
type CommitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommitMutation
}

// SetAuthor sets the "author" field.
func (cuo *CommitUpdateOne) SetAuthor(a any) *CommitUpdateOne {
	cuo.mutation.SetAuthor(a)
	return cuo
}

// SetURL sets the "url" field.
func (cuo *CommitUpdateOne) SetURL(s string) *CommitUpdateOne {
	cuo.mutation.SetURL(s)
	return cuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (cuo *CommitUpdateOne) SetNillableURL(s *string) *CommitUpdateOne {
	if s != nil {
		cuo.SetURL(*s)
	}
	return cuo
}

// SetDate sets the "date" field.
func (cuo *CommitUpdateOne) SetDate(t time.Time) *CommitUpdateOne {
	cuo.mutation.SetDate(t)
	return cuo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (cuo *CommitUpdateOne) SetNillableDate(t *time.Time) *CommitUpdateOne {
	if t != nil {
		cuo.SetDate(*t)
	}
	return cuo
}

// Mutation returns the CommitMutation object of the builder.
func (cuo *CommitUpdateOne) Mutation() *CommitMutation {
	return cuo.mutation
}

// Where appends a list predicates to the CommitUpdate builder.
func (cuo *CommitUpdateOne) Where(ps ...predicate.Commit) *CommitUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommitUpdateOne) Select(field string, fields ...string) *CommitUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Commit entity.
func (cuo *CommitUpdateOne) Save(ctx context.Context) (*Commit, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommitUpdateOne) SaveX(ctx context.Context) *Commit {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommitUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommitUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CommitUpdateOne) sqlSave(ctx context.Context) (_node *Commit, err error) {
	_spec := sqlgraph.NewUpdateSpec(commit.Table, commit.Columns, sqlgraph.NewFieldSpec(commit.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Commit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commit.FieldID)
		for _, f := range fields {
			if !commit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Author(); ok {
		_spec.SetField(commit.FieldAuthor, field.TypeJSON, value)
	}
	if value, ok := cuo.mutation.URL(); ok {
		_spec.SetField(commit.FieldURL, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Date(); ok {
		_spec.SetField(commit.FieldDate, field.TypeTime, value)
	}
	_node = &Commit{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
